<?php
use \ArtfulRobot\CsvParser;

function etgenderpaygap_menu() {
  return [
    'admin/configure/etgenderpaygap' => [
      'page callback' => 'etgenderpaygap__page_load_data',
      'access callback' => TRUE, // xxx
    ],

    'etgenderpaygap/matches' => [
      'page callback'   => 'etgenderpaygap__page_matches',
      'access callback' => TRUE, //etgenderpaygap__access_matches
    ],

    'etgenderpaygap/submit' => [
      'page callback'   => 'etgenderpaygap__page_submit',
      'access callback' => TRUE,
    ],
  ];
}

function etgenderpaygap__page_load_data() {

  require_once __DIR__ . "/vendor/CsvParser.php";

  $csv = CsvParser::createFromFile(__DIR__ .'/src/companies.csv');

  db_query('TRUNCATE etgenderpaygap_companies');

  foreach ($csv as $row) {
    $x = [
        'name' => trim($row->EmployerName),
        'paygap_hours' => (float) $row->DiffMeanHourlyPercent,
        'paygap_bonus' => $row->DiffMeanBonusPercent,
      ];
    $x['paygap_bonus'] = empty($x['paygap_bonus']) ? NULL : (float) $x['paygap_bonus'];
    if (!$x['name']) {
      continue;
    }
    db_insert('etgenderpaygap_companies')
      ->fields($x)
      ->execute();
  }

}
/**
 * JSON API.
 */
function etgenderpaygap__page_matches() {
  $matcher = new ETGenderPayGapMatcher($_GET['key'] ?? '');
  $output = $matcher->matches();
  drupal_json_output($output);
  drupal_exit();
}
/**
 * Restrict access to XHR requests.
 */
function etgenderpaygap__access_matches() {
  return (isset($_SERVER['HTTP_X_REQUESTED_WITH']) && strtolower($_SERVER['HTTP_X_REQUESTED_WITH']) === 'xmlhttprequest');
}

/**
 * JSON API.
 *
 * Takes params:
 * - company (id)
 * - salary (required)
 * - bonus (optional)
 */
function etgenderpaygap__page_submit() {
  $company_id = (int) $_POST['company'] ?? 0;
  $company = db_query(
    'SELECT * FROM etgenderpaygap_companies WHERE id = :theid;',
    [':theid' => $company_id]
  )->fetchAssoc();
  if (!$company) {
    // Spam?
    drupal_json_output(['error' => 'Invalid request']);
    drupal_exit();
  }
  if (empty($_POST['salary'])) {
    drupal_json_output(['error' => 'Invalid request']);
    drupal_exit();
  }
  // OK got everything we need.
  $loss = 0;
  if ($company['paygap_hours'] > 0) {
    $loss += $company['paygap_hours'] / 100 * $_POST['salary'];
  }
  if ($company['paygap_bonus'] > 0 && !empty($_POST['bonus'])) {
    $loss += $company['paygap_bonus'] / 100 * $_POST['bonus'];
  }
  $total_loss = variable_get('etgenderpaygap_loss', 0) + $loss;
  $count = variable_get('etgenderpaygap_count', 0) + 1;
  variable_set('etgenderpaygap_loss', $total_loss);
  variable_set('etgenderpaygap_count', $count);

  $output = [
    'count' => $count,
    'loss' => $total_loss,
  ];

  drupal_json_output($output);
  drupal_exit();
}
class ETGenderPayGapMatcher
{
  /** @var array of search keys. */
  protected $keys;

  public function __construct($search_key) {
    $key = strtolower(trim($_GET['company']));
    $this->keys = array_filter(preg_split('/[^a-z0-9]+/', $key));
  }
  /**
   *
   * @return Array of matching rows (limit of 10)
   */
  public function matches() {
    if (!$this->keys) {
      return [];
    }

    // First assume each key is sequential and must exist.
    $start = implode('%', $this->keys) . '%';
    $anywhere = '%' . $start;
    $matches = db_query("
        SELECT *
        FROM etgenderpaygap_companies
        WHERE name LIKE :anywhere
        ORDER BY NOT name LIKE :start, name
        LIMIT 10", [':anywhere' => $anywhere, ':start' => $start])
      ->fetchAllAssoc('id');
    $count = count($matches);

    if ($count == 10) {
      // We hit 10, are there more?
      $count = (int) db_query("
        SELECT COUNT(*) c
        FROM etgenderpaygap_companies
        WHERE name LIKE :anywhere", [':anywhere' => $anywhere])
      ->fetchField();
    }

    if ($count == 0) {
      // We didn't find any. Try searching in any order.
      $params = [];
      $sql = [];
      foreach ($this->keys as $i => $k) {
        $params[":key$i"] = '%' . $k . '%';
        $sql[] = "name LIKE :key$i";
      }
      $sql = "SELECT * FROM etgenderpaygap_companies WHERE " . implode(' AND ', $sql)
        . " ORDER BY name";
      $result = db_query($sql, $params);
      $count = $result->rowCount();
      $i=0;
      while ($row = $result->fetchAssoc()) {
        $matches[] = $row;
        if (++$i == 10) {
          break;
        }
      }
    }

    return [
      'matches' => $matches,
      'count' => $count,
    ];
    if ($matches) {
      return $matches;
    }
  }
}
